name: Build LineageOS 21 for SM-A225F

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev \
          libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3

      - name: Set up repo tool
        run: |
          sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
          sudo chmod a+x /usr/local/bin/repo

      - name: Initialize and sync source
        run: |
          mkdir -p ~/android/lineage
          cd ~/android/lineage

          repo init -u https://github.com/LineageOS/android.git -b lineage-21.0
          repo sync -c --no-clone-bundle --no-tags -j4

      - name: Clone device, vendor, and kernel trees
        run: |
          cd ~/android/lineage

          git clone https://github.com/Samsung-Helio-G80-Devs/android_device_samsung_a22.git -b lineage-21 device/samsung/a22
          git clone https://github.com/Samsung-Helio-G80-Devs/android_vendor_samsung_a22.git -b lineage-21 vendor/samsung/a22
          git clone https://github.com/VH-Devices/android_kernel_samsung_a22.git -b lineage-21 kernel/samsung/a22

      - name: Build ROM
        run: |
          cd ~/android/lineage

          export ALLOW_MISSING_DEPENDENCIES=true
          export BUILD_USERNAME="github"
          export BUILD_HOSTNAME="actions"

          source build/envsetup.sh
          lunch lineage_a225f-userdebug
          mka bacon -j2
